### ISSUE TITLE
Cannot open sublime merger in vs code under ubuntu

### ISSUE THREAD

**Issue by DigitalPig** [morrislaptop/vscode-open-in-sublime-merge#1]
Thanks for the awesome extension. I have both Mac for work and Ubuntu for personal laptop. The mac vs code works perfect while the ubuntu one always complains about "no git repo found". Any idea how to solve this issue?

I can provide more info if needed.

**Comment by DigitalPig** [comment]
I guess the issue is because of line here:
https://github.com/morrislaptop/vscode-open-in-sublime-merge/blob/8ae53ea9e04c333fa09b22cfbc254419f2535444/extension.js#L50

looks like sublime merger does have different names under different systems. Under linux, it is `smerge`.

**Comment by morrislaptop** [comment]
Can you try the latest commit and see if that works? I'll publish if all good

**Comment by MuizU** [comment]
I get this same issue even though I have installed the latest version of the extension. I'm using manjaro deepin.

**Comment by simonprague** [comment]
I still get the same error: No git repo found

**Comment by simonprague** [comment]
Is it possible it's caused by non-standard location of the .code-workspace file? For example mine is not in the root of the workspace but in a subfolder. Also my project has multiple root folders.

Interestingly this extension works on some projects but fails on others. Anyway it's really frustrating as I really like this command. I wish I could provide some logs but I'm not sure how.
